### ISSUE TITLE
To make it better 

### ISSUE THREAD

**Issue by HenrywooChem** [pliolios/curvedigitizer#2]
Hi there,
Thanks for the excellence work you have done. Here are three comments from my side:
1. In line 56: img = mpimg.imread(filein) ,here need another parameter like this: "img = mpimg.imread(filein,0) ".
2. In line 69: "Left click: select point; Right click: undo; Middle click: finish","middle click " means Enter? because my middle click have no effect.
3. It will be nice if the selected picture could be zoomed larger for points clicking.
Cool codes!

**Comment by pliolios** [comment]
Hi HenrywooChem,
Thank you for your comments. Here is my reply to your points:
1. The second parameter is optional so I didn't use it.
2. I don't know why middle click doesn't work for you. In my PC works as an "Enter".
3. Zooming changes the number of pixels (coordinates) of the image and requires special treatment. For example, if one set the scaling with the original image size and then zooms to digitize the curves, the code should recalculate the scale etc. Maybe in the future I will add this feature.
Pantelis
